In [1]:
import tensorflow as tf

In [22]:
graph1 = tf.Graph()

with graph1.as_default():
    a = tf.constant([2], name = 'a')
    b = tf.constant([3], name = 'b')
    
a

<tf.Tensor 'a:0' shape=(1,) dtype=int32>

In [11]:
# running session using with
with tf.Session(graph = graph1) as sess:
    result = sess.run(a)
    print(result)

[2]


In [12]:
# running session not using with block
sess = tf.Session(graph = graph1)
result = sess.run(a)
print(result)
sess.close() #don't forget to close the session

[2]


In [23]:
# within the graph constants
with graph1.as_default():
    c=tf.multiply(a,b)
with tf.Session(graph=graph1) as sess:
    result = sess.run(c)
    print(result)

[6]


In [21]:
# without any graph
a1 = tf.constant([4], name = 'const_a')
b1 = tf.constant([5], name = 'const_b')

with tf.Session() as sess:
    result = sess.run(tf.multiply(a1,b1))
    print(result)

[20]


In [24]:
graph2 = tf.Graph()
with graph2.as_default():
    Scalar = tf.constant(2)
    Vector = tf.constant([5,6,2])
    Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )
with tf.Session(graph = graph2) as sess:
    result = sess.run(Scalar)
    print ("Scalar (1 entry):\n %s \n" % result)
    result = sess.run(Vector)
    print ("Vector (3 entries) :\n %s \n" % result)
    result = sess.run(Matrix)
    print ("Matrix (3x3 entries):\n %s \n" % result)
    result = sess.run(Tensor)
    print ("Tensor (3x3x3 entries) :\n %s \n" % result)

Scalar (1 entry):
 2 

Vector (3 entries) :
 [5 6 2] 

Matrix (3x3 entries):
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Tensor (3x3x3 entries) :
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



In [26]:
Tensor.shape

TensorShape([Dimension(3), Dimension(3), Dimension(3)])

In [28]:
graph3 = tf.Graph()
with graph3.as_default():
    matrix_one = tf.constant([[2,3],[3,4]])
    matrix_two = tf.constant([[2,3],[3,4]])
    
    mul_oper = tf.matmul(matrix_one,matrix_two)
    
with tf.Session(graph = graph3) as sess:
    result = sess.run(mul_oper)
    print(result)

[[13 18]
 [18 25]]


In [29]:
# variables
v = tf.Variable(0)
# simple counter using tf.assign(reference_variable, value_to_update)
update = tf.assign(v, v+1)
# intiate variables
init = tf.global_variables_initializer()

In [30]:
#run
with tf.Session() as sess:
    result = sess.run(init)
    print(result)
    for i in range(3):
        sess.run(update)
        print(sess.run(v))

None
1
2
3


In [31]:
# placeholders
# If you want to feed data to a TensorFlow graph from 
# outside a graph, you will need to use placeholders

p = tf.placeholder(tf.float32)
p1 = p*2

In [33]:
with tf.Session() as sess:
    result = sess.run(p1, feed_dict = {p:3.5})
    print(result)

7.0


In [35]:
# trying with a matrix
dictionary={p: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

with tf.Session() as sess:
    result = sess.run(p1,feed_dict=dictionary)
    print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


In [36]:
graph5 = tf.Graph()
with graph5.as_default():
    a = tf.constant([5])
    b = tf.constant([2])
    c = tf.add(a,b)
    d = tf.multiply(a,b)
    
with tf.Session(graph = graph5) as sess:
    result = sess.run(c)
    print('c =: %s' % result)
    result = sess.run(d)
    print('d =: %s' % result)

c =: [7]
d =: [10]
