In [1]:
import numpy as np

h = [2, 1, 0]
x = [3, 4, 5]

y = np.convolve(x, h) 
y

array([ 6, 11, 14,  5,  0])

In [2]:
print("Compare with the following values from Python: y[0] = {0} ; y[1] = {1}; y[2] = {2}; y[3] = {3}; y[4] = {4}".format(y[0], y[1], y[2], y[3], y[4])) 

Compare with the following values from Python: y[0] = 6 ; y[1] = 11; y[2] = 14; y[3] = 5; y[4] = 0


In [3]:
import numpy as np

x = [6, 2]
h = [1, 2, 5, 4]

y = np.convolve(x, h, "full")  #now, because of the zero padding, the final dimension of the array is bigger
y

array([ 6, 14, 34, 34,  8])

In [4]:
y1 = np.convolve(x, h, "same")

y1

array([ 6, 14, 34, 34])

In [5]:
y2 = np.convolve(x, h, "valid")

y2

array([14, 34, 34])

In [6]:
from scipy import signal as sg

I= [[255,   7,  3],
    [212, 240,  4],
    [218, 216, 230],]

g= [[-1, 1]]

print('without zero padding')
print(sg.convolve( I, g, 'valid'))

print('with zero padding')
print(sg.convolve( I, g))

without zero padding
[[248   4]
 [-28 236]
 [  2 -14]]
with zero padding
[[-255  248    4    3]
 [-212  -28  236    4]
 [-218    2  -14  230]]


C:\Users\madhu\Anaconda3\envs\tensorflow1\lib\site-packages\scipy\signal\signaltools.py:491: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return x[reverse].conj()
C:\Users\madhu\Anaconda3\envs\tensorflow1\lib\site-packages\scipy\signal\signaltools.py:251: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  in1zpadded[sc] = in1.copy()


In [7]:
from scipy import signal as sg

I= [[255,   7,  3],
    [212, 240,  4],
    [218, 216, 230],]

g= [[-1,  1],
    [ 2,  3],]

print ('With zero padding \n')
print ('{0} \n'.format(sg.convolve( I, g, 'full')))
# The output is the full discrete linear convolution of the inputs. 
# It will use zero to complete the input matrix

print ('With zero padding_same_ \n')
print ('{0} \n'.format(sg.convolve( I, g, 'same')))
# The output is the full discrete linear convolution of the inputs. 
# It will use zero to complete the input matrix


print ('Without zero padding \n')
print (sg.convolve( I, g, 'valid'))
# The 'valid' argument states that the output consists only of those elements 
#that do not rely on the zero-padding.

With zero padding 

[[-255  248    4    3]
 [ 298  751  263   13]
 [ 206 1118  714  242]
 [ 436 1086 1108  690]] 

With zero padding_same_ 

[[-255  248    4]
 [ 298  751  263]
 [ 206 1118  714]] 

Without zero padding 

[[ 751  263]
 [1118  714]]


C:\Users\madhu\Anaconda3\envs\tensorflow1\lib\site-packages\scipy\signal\signaltools.py:491: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return x[reverse].conj()
C:\Users\madhu\Anaconda3\envs\tensorflow1\lib\site-packages\scipy\signal\signaltools.py:251: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  in1zpadded[sc] = in1.copy()


In [8]:
import tensorflow as tf

# graph

input = tf.Variable(tf.random_normal([1, 10, 10, 1]))
filter = tf.Variable(tf.random_normal([3, 3, 1, 1]))
op = tf.nn.conv2d(input, filter, strides = [1,1,1,1], padding='VALID')
op2 = tf.nn.conv2d(input, filter, strides = [1,1,1,1], padding = 'SAME')

# initilization 
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    
    print("Input \n")
    print('{0} \n'.format(input.eval()))
    print("Filter/Kernel \n")
    print('{0} \n'.format(filter.eval()))
    print("Result/Feature Map with valid positions \n")
    result = sess.run(op)
    print(result)
    print('\n')
    print("Result/Feature Map with padding \n")
    result2 = sess.run(op2)
    print(result2)


Input 

[[[[ 1.1440651 ]
   [ 0.73692447]
   [-0.00758464]
   [-0.8486366 ]
   [ 0.57775915]
   [ 2.046371  ]
   [-0.5953967 ]
   [ 0.27711588]
   [ 0.79367816]
   [ 0.36801946]]

  [[-0.22549531]
   [-0.76813316]
   [-0.5864557 ]
   [-0.4180337 ]
   [-0.64330506]
   [-0.4517611 ]
   [ 0.13043533]
   [ 0.6591065 ]
   [ 1.4882228 ]
   [ 1.9619145 ]]

  [[-0.4810862 ]
   [ 0.04267517]
   [-2.3506007 ]
   [-0.39132914]
   [ 2.3838825 ]
   [-2.0559065 ]
   [ 2.7667742 ]
   [ 0.63090044]
   [ 0.91079414]
   [ 1.0097035 ]]

  [[ 1.2557724 ]
   [ 0.9831221 ]
   [ 2.3871295 ]
   [-0.08721773]
   [ 0.1421119 ]
   [-1.8639817 ]
   [ 0.2944906 ]
   [ 0.12814055]
   [ 0.7857296 ]
   [-0.11051561]]

  [[-1.0216095 ]
   [-1.3731773 ]
   [-1.9153916 ]
   [-1.9739927 ]
   [-0.15390603]
   [ 0.3010487 ]
   [ 0.6925515 ]
   [ 0.9933659 ]
   [ 0.8449992 ]
   [-0.45239148]]

  [[-0.20524056]
   [ 0.80298275]
   [ 0.2031048 ]
   [-0.50262076]
   [-1.3680948 ]
   [ 1.1583067 ]
   [-0.41019264]
   [ 2.029177